version: "3.18"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: transitclock
      POSTGRES_DB: transitclock
    ports:
      - "5432:5432"
  gtfsrt-validator:
    image: ghcr.io/mobilitydata/gtfs-realtime-validator:latest
    ports:
      - "9090:8080"
  transitclock:
    image: wkulesza/transitclock-server:latest
    depends_on:
      - db
    environment:
      AGENCYID: ID
      AGENCYNAME: transitclock
      TZ: "Europe/Warsaw"
      GTFS_URL: https://example/gtfs.zip
      GTFSRTVEHICLEPOSITIONS: https://api.example
      PGPASSWORD: transitclock
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_PORT_5432_TCP_PORT: 5432
    volumes:
      - ./transitclock.properties:/app/config/transitclock.properties
    ports:
      - "8080:8080"
    command:
      - --gtfs-url
      - https://example/gtfs.zip
